### ISSUE TITLE
Upload a model

### ISSUE THREAD

**Issue by todotson** [ethz-pes/AI-mag#1]
Hello,

Can you add a trained model that I can use without creating a dataset?

**Comment by otvam** [comment]
Hello,
The complete dataset and the trained ANN are available in the release. 
[https://github.com/ethz-pes/AI-mag/releases/download/v3.6/data.zip](https://github.com/ethz-pes/AI-mag/releases/download/v3.6/data.zip)
Best regards

**Comment by todotson** [comment]
Thanks, I was looking within the repo files. Apparently it was a separate asset.
