### ISSUE TITLE
Error using load

### ISSUE THREAD

**Issue by javadshamsicodes** [ethz-pes/AI-mag#3]
Hello Mr.Guillod
I got the below error when I ran the run_design_compute_single:
Unable to find file or directory 'dataset/export.mat'.
I unzipped the 'data.zip' before and put the folder in the dataset.

**Comment by otvam** [comment]
Hi Javad,

Where did you unpack 'data.zip'? The data should be unpacked at the root of the project:
	- the 'dataset' folder in data.zip should replace the 'dataset' folder in the source package
	- the 'design' folder in data.zip should replace the 'design' folder in the source package
	
Let me know if the problem is persisting!

Best,
Thomas
