### ISSUE TITLE
Is this a bug? do you mean to compare x_window with y_window here?

### ISSUE THREAD

**Issue by BCheong1990** [ethz-pes/AI-mag#4]
https://github.com/ethz-pes/AI-mag/blob/5239ca782d1a9e0f344de3db31ec3291fd671a54/src/inductor_dataset/%2Bdataset/get_extend_inp.m#L125

**Comment by otvam** [comment]
Definitely a bug! I guess is was not found before because y_window > x_window for most inductor designs.
It has been corrected, thank you very much for finding and reporting the problem!

**Comment by BCheong1990** [comment]
You're welcome!
